# Generated by Django 2.0.2 on 2019-03-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='honey',
            new_name='hunter',
        ),
    ]
